# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-24 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadjob', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadjob',
            options={'verbose_name': '\u70b9\u8bc4\u4f5c\u4e1a', 'verbose_name_plural': '\u70b9\u8bc4\u4f5c\u4e1a'},
        ),
    ]
