# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-24 22:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u79d1\u76ee\u540d')),
                ('decs', models.CharField(default='', max_length=500, verbose_name='\u79d1\u76ee\u8bf4\u660e')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8003\u8bd5\u79d1\u76ee',
                'verbose_name_plural': '\u8003\u8bd5\u79d1\u76ee',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operation.CourseList', verbose_name='\u6240\u5c5e\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u8bd5\u9898\u5217\u8868',
                'verbose_name_plural': '\u8bd5\u9898\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='PaperCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.IntegerField(verbose_name='\u9898\u76ee')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u8bd5\u9898\u4e34\u65f6\u5217\u8868',
                'verbose_name_plural': '\u8bd5\u9898\u4e34\u65f6\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='PaperList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u8bd5\u5377\u540d')),
                ('is_allow', models.BooleanField(default=False, verbose_name='\u662f\u5426\u542f\u7528')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.CourseList', verbose_name='\u6240\u5c5e\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u8bd5\u5377\u5217\u8868',
                'verbose_name_plural': '\u8bd5\u5377\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(choices=[('xz', '\u9009\u62e9\u9898'), ('pd', '\u5224\u65ad\u9898'), ('mxz', '\u591a\u9009')], default='xz', max_length=4, verbose_name='\u9898\u76ee\u7c7b\u578b')),
                ('content', models.TextField(verbose_name='\u9898\u76ee\u5185\u5bb9')),
                ('answer', models.TextField(verbose_name='\u6b63\u786e\u7b54\u6848')),
                ('choice_a', models.TextField(default='A.', verbose_name='A\u9009\u9879')),
                ('choice_b', models.TextField(default='B.', verbose_name='B\u9009\u9879')),
                ('choice_c', models.TextField(default='C.', verbose_name='C\u9009\u9879')),
                ('choice_d', models.TextField(default='D.', verbose_name='D\u9009\u9879')),
                ('choice_e', models.TextField(default='E.', verbose_name='E\u9009\u9879')),
                ('choice_f', models.TextField(default='F.', verbose_name='F\u9009\u9879')),
                ('score', models.IntegerField(default=0, verbose_name='\u5206\u503c')),
                ('note', models.TextField(default='\u95ee\u7b54\u9898\u5728\u6b64\u5904\u505a\u7b54', verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('boolt', models.TextField(default='\u5bf9', verbose_name='\u5224\u65ad\u6b63\u8bef\u6b63\u786e\u9009\u9879')),
                ('boolf', models.TextField(default='\u9519', verbose_name='\u5224\u65ad\u6b63\u8bef\u9519\u8bef\u9009\u9879')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('choice_num', models.IntegerField(default=4, verbose_name='\u9009\u9879\u6570')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.CourseList', verbose_name='\u8003\u8bd5\u79d1\u76ee')),
            ],
            options={
                'verbose_name': '\u9898\u5e93',
                'verbose_name_plural': '\u9898\u5e93',
            },
        ),
        migrations.CreateModel(
            name='UserAnswerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='\u7528\u6237\u7b54\u6848')),
                ('score', models.IntegerField(verbose_name='\u5f97\u5206')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u4f5c\u7b54\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.CourseList', verbose_name='\u8bfe\u7a0b')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Paper', verbose_name='\u8bd5\u5377')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u505a\u9898\u8bb0\u5f55',
                'verbose_name_plural': '\u7528\u6237\u505a\u9898\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0, verbose_name='\u603b\u5206')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u5f55\u5165\u65f6\u95f4')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='\u59d3\u540d')),
                ('zhiwu', models.CharField(default='', max_length=50, verbose_name='\u804c\u52a1')),
                ('leibie', models.CharField(default='', max_length=50, verbose_name='\u7c7b\u522b')),
                ('danwei', models.CharField(default='', max_length=50, verbose_name='\u5355\u4f4d')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.PaperList', verbose_name='\u8bd5\u5377')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u603b\u5206',
                'verbose_name_plural': '\u7528\u6237\u603b\u5206',
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.PaperList', verbose_name='\u8bd5\u5377\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='paper',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Question', verbose_name='\u9898\u76ee'),
        ),
    ]
