# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-12 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExplationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=10, verbose_name='\u79d1\u76ee')),
                ('name', models.CharField(max_length=10, verbose_name='\u5e74\u4efd')),
                ('unit', models.CharField(max_length=10, verbose_name='\u7b2c\u51e0\u5957')),
                ('desc', models.CharField(max_length=500, verbose_name='\u8bfe\u7a0b\u63cf\u8ff0')),
                ('video_name', models.CharField(max_length=100, verbose_name='\u89c6\u9891\u540d\u79f0')),
                ('download', models.FileField(upload_to='question/resource/%Y/%m', verbose_name='\u8d44\u6e90\u6587\u4ef6')),
                ('url', models.CharField(default='', max_length=200, verbose_name='\u8bbf\u95ee\u5730\u5740')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('category', models.CharField(default='\u540e\u7aef\u5f00\u53d1', max_length=20, verbose_name='\u8bfe\u7a0b\u7c7b\u522b')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='\u8bfe\u7a0b\u6807\u7b7e')),
                ('youneed_know', models.CharField(default='', max_length=300, verbose_name='\u8bfe\u7a0b\u987b\u77e5')),
                ('teacher_tell', models.CharField(default='', max_length=300, verbose_name='\u8001\u5e08\u544a\u8bc9\u4f60')),
                ('degree', models.CharField(choices=[('cj', '\u521d\u7ea7'), ('zj', '\u4e2d\u7ea7'), ('gj', '\u9ad8\u7ea7')], max_length=2, verbose_name='\u96be\u5ea6')),
            ],
            options={
                'verbose_name': '\u771f\u9898\u8bb2\u89e3',
                'verbose_name_plural': '\u771f\u9898\u8bb2\u89e3',
            },
        ),
        migrations.CreateModel(
            name='ManageQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=20, verbose_name='\u8bfe\u7a0b')),
                ('chapter', models.CharField(max_length=20, verbose_name='\u7ae0\u8282')),
                ('name', models.CharField(max_length=20, verbose_name='\u7ae0\u8282\u540d\u79f0')),
                ('download', models.FileField(upload_to='classs/resource/%Y/%m', verbose_name='\u8d44\u6e90\u6587\u4ef6')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9898\u578b\u7ba1\u7406',
                'verbose_name_plural': '\u9898\u578b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='TextOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30, verbose_name='\u9898\u76ee')),
                ('line', models.CharField(max_length=100, verbose_name='\u94fe\u63a5')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5728\u7ebf\u6d4b\u8bc4',
                'verbose_name_plural': '\u5728\u7ebf\u6d4b\u8bc4',
            },
        ),
    ]
