# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-24 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explationquestion',
            name='category',
            field=models.CharField(blank=True, default='\u8003\u7814\u82f1\u8bed', max_length=20, null=True, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='explationquestion',
            name='image',
            field=models.ImageField(default='courses/2019/05/b8.jpg', upload_to='courses/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
        migrations.AlterField(
            model_name='explationquestion',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='\u8bfe\u7a0b\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='explationquestion',
            name='teacher_tell',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='\u8001\u5e08\u544a\u8bc9\u4f60'),
        ),
        migrations.AlterField(
            model_name='explationquestion',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='explationquestion',
            name='youneed_know',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
    ]
