# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-15 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.CharField(max_length=20, verbose_name='\u9898\u76ee\u7c7b\u578b')),
                ('title', models.CharField(max_length=500, verbose_name='\u9898\u76ee')),
                ('standardAnswer', models.CharField(max_length=50, null=True, verbose_name='\u6807\u51c6\u7b54\u6848')),
                ('teacher', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5f55\u5165\u6559\u5e08')),
            ],
            options={
                'verbose_name': '\u5f55\u5165\u9898\u5e93',
                'verbose_name_plural': '\u5f55\u5165\u9898\u5e93',
            },
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=5, verbose_name='\u5b66\u751f\u6210\u7ee9')),
                ('student', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6d4b\u8bd5\u5b66\u751f')),
            ],
            options={
                'verbose_name': '\u5b66\u751f\u6210\u7ee9',
                'verbose_name_plural': '\u5b66\u751f\u6210\u7ee9',
            },
        ),
    ]
