# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-04-22 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190422_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='classroom',
            field=models.CharField(default='0', max_length=20, verbose_name='\u73ed\u7ea7\u53f7'),
        ),
    ]
