# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-06 22:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AskQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u5b66\u751f\u95ee\u9898')),
                ('qusetion', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u6559\u5e08\u56de\u7b54')),
                ('ask_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='\u63d0\u95ee\u5b66\u751f')),
                ('question_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='\u56de\u7b54\u6559\u5e08')),
            ],
            options={
                'verbose_name': '\u95ee\u9898\u7b54\u7591',
                'verbose_name_plural': '\u95ee\u9898\u7b54\u7591',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=15, verbose_name='\u73ed\u7ea7\u53f7')),
                ('yard', models.CharField(max_length=10, verbose_name='\u6240\u5c5e\u9662')),
                ('class_info', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u73ed\u7ea7\u516c\u544a')),
                ('grade', models.CharField(max_length=10, verbose_name='\u5e74\u7ea7')),
                ('profession', models.CharField(max_length=10, verbose_name='\u4e13\u4e1a')),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%Y/%m')),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7\u4fe1\u606f',
                'verbose_name_plural': '\u73ed\u7ea7\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='StudentManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15, verbose_name='\u5b66\u53f7')),
                ('review', models.FileField(blank=True, max_length=300, null=True, upload_to='classs/resource/%Y/%m', verbose_name='\u4f5c\u4e1a\u68c0\u67e5')),
                ('answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4f5c\u4e1a\u70b9\u8bc4')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classs.ClassRoom', verbose_name='\u73ed\u7ea7')),
                ('student_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5b66\u751f\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u5b66\u751f\u7ba1\u7406',
                'verbose_name_plural': '\u5b66\u751f\u7ba1\u7406',
            },
        ),
    ]
