# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-09 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmanagement',
            name='review',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='classs/resource/%Y/%m', verbose_name='\u4f5c\u4e1a\u68c0\u67e5'),
        ),
    ]
