# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-24 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0002_auto_20190509_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='image',
            field=models.ImageField(default='image/2019/04/6.jpg', upload_to='image/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classs.ClassRoom', verbose_name='\u73ed\u7ea7'),
        ),
    ]
